SET SQL DIALECT 3;

CREATE DATABASE 'MKDATA.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET WIN1252 COLLATION Win_PTBR;

CREATE GENERATOR GEN_CLICOD;

CREATE TABLE CLIENTES (
    CLICOD     INTEGER     NOT NULL,
    CLIDTCAD   DATE        default 'NOW',
    CLINOME    VARCHAR(45) NOT NULL,
    CLIPESSOA  VARCHAR(1)  default 'F',
    CLIIERG    VARCHAR(20),
    CLICPFCNPJ VARCHAR(20),
    CLIATIVO   VARCHAR(1)  default 'S'
);

CREATE TABLE ENDCLI (
    ENDCLICOD   INTEGER NOT NULL,
    ENDCLIEND   VARCHAR(45),
    ENDCLINUM   VARCHAR(6),
    ENDCLICOMPL VARCHAR(25),
    ENDCLIBAI   VARCHAR(25),
    ENDCLICID   VARCHAR(30),
    ENDCLIUF    VARCHAR(20),
    ENDCLIPAIS  VARCHAR(25),
    ENDCLICEP   VARCHAR(10)
);

CREATE TABLE TELCLI (
    TELCLICOD    INTEGER NOT NULL,
    TELCLINUMERO VARCHAR(14),
    TELCLIOBS    VARCHAR(15)
);

ALTER TABLE CLIENTES ADD CONSTRAINT CHK_CLIPESSOA check (CliPessoa in ('F', 'J'));
ALTER TABLE CLIENTES ADD CONSTRAINT CHK_CLIATIVO  check (CliAtivo  in ('S', 'N'));
ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES   PRIMARY KEY (CLICOD);
ALTER TABLE ENDCLI   ADD CONSTRAINT FK_ENDCLICOD  FOREIGN KEY (ENDCLICOD) REFERENCES CLIENTES (CLICOD) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE TELCLI   ADD CONSTRAINT FK_TELCLICOD  FOREIGN KEY (TELCLICOD) REFERENCES CLIENTES (CLICOD) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE UNIQUE INDEX UNQ_CLINOME    ON CLIENTES (CLINOME);
CREATE UNIQUE INDEX UNQ_CLIIERG    ON CLIENTES (CLIIERG);
CREATE UNIQUE INDEX UNQ_CLICPFCNPJ ON CLIENTES (CLICPFCNPJ);

CREATE VIEW VClientes as
  SELECT
    CLICOD     as "Código",
    CLINOME    as "Nome",
    CLIDTCAD   as "Cadastro",
    CLIPESSOA  as "Pessoa",
    CLIIERG    as "IE/RG",
    CLICPFCNPJ as "CPF/CNPJ",
    CLIATIVO   as "Ativo"
FROM Clientes;

SET TERM ^ ;

CREATE OR ALTER TRIGGER TR_GERACLICOD FOR CLIENTES
ACTIVE AFTER INSERT OR UPDATE POSITION 0
AS
BEGIN
  IF (New.CliCod = 0) THEN
    UPDATE Clientes SET CliCod = Gen_Id(Gen_CliCod, 1) WHERE CliCod = 0;
END
^

CREATE OR ALTER TRIGGER TR_VERCLIENTES FOR CLIENTES
ACTIVE BEFORE INSERT OR UPDATE POSITION 1
AS
begin
  if (New.CliCod is Null) then
    New.CliCod = 0;
  New.CliNome = Upper(New.CliNome);
end
^

SET TERM ; ^
